describe("28 10:54", () => {
  it("tests 28 10:54", async () => {
    await browser.setWindowSize(1351, 294)
    await browser.url("https://mygs-uat.girlscouts.org/")
    await expect(browser).toHaveUrl("https://mygs-uat.girlscouts.org/")
    await browser.url("https://mygs-uat.girlscouts.org/")
    await expect(browser).toHaveUrl("https://mygs-uat.girlscouts.org/")
    await browser.$("#loginBtn").click()
    await browser.$("//*[@id=\"Default-RegistrationLogin\"]/div[1]/form/div[2]/div[3]/div[2]/input").setValue("LTOct11adult00815@yopmail.com")
    await browser.$("//*[@id=\"Default-RegistrationLogin\"]/div[1]/form/div[2]/div[3]/div[4]/input").setValue("Test123#")
    await browser.$("//*[@id=\"Default-RegistrationLogin\"]/div[2]/form/div[1]/div[3]/div/input").setValue("LTOct11adult00815@yopmail.com")
    await browser.$("//*[@id=\"Default-RegistrationLogin\"]/div[2]/form/div[1]/div[4]/input").setValue("Test123#")
    await browser.$("#gigya-loginID-79158041058054780").setValue("LTOct11adult00815@yopmail.com")
    await browser.$("#gigya-password-96764271754460130").setValue("Test123#")
    await browser.$("#gigya-loginID-79158041058054780").click()
    await browser.$("#gigya-loginID-79158041058054780").setValue("LTOct11adult00818@yopmail.com")
    await browser.$("aria/LOG IN").click()
    await browser.$("//*[@id=\"Default-RegistrationLogin\"]/div[1]/form/div[2]/div[3]/div[2]/input").setValue("LTOct11adult00818@yopmail.com")
    await browser.$("//*[@id=\"Default-RegistrationLogin\"]/div[2]/form/div[1]/div[3]/div/input").setValue("LTOct11adult00818@yopmail.com")
    await browser.$("//*[@id=\"slide-ngb-slide-0\"]/gs-card/div/button/span[1]").click()
    await browser.$("#myAccountBtn").click()
    await browser.$("//*[@id=\"slide-ngb-slide-0\"]/gs-card/div/button/span[2]").click()
    await browser.$("aria/My Household[role=\"link\"]").click()
    await browser.$("aria/Register a new household member ").click()
    await browser.$("//*[@id=\"ngb-nav-0-panel\"]/app-troops-search/form/gs-main-wrap/div/gs-form-row[5]/gs-form-input-wrap/gs-form-row/div[3]/label/span[1]").click()
    await browser.$("//*[@id=\"ngb-nav-0-panel\"]/app-troops-search/form/gs-main-wrap/div/gs-form-row[5]/gs-form-input-wrap/gs-form-row/div[3]").click()
    await browser.$("aria/SEARCH").click()
    await browser.$("//*[@id=\"troop-detail-data-0\"]/div[6]/div/div/div[1]/div/div/div/span[2]/button").click()
    await browser.$("aria/ADD DETAILS").click()
    await browser.$("//*[@id=\"type-B-36701085-0\"]/div[1]/div/div[2]").click()
    await browser.$("#a603ccd3cb29-0").click()
    await browser.$("aria/Girl first name").click()
    await browser.$("aria/Girl first name").setValue("Jelly")
    await browser.performActions([{
      type: 'key',
      id: 'keyboard',
      actions: [{ type: 'keyDown', value: '' }]
    }])
    await browser.performActions([{
      type: 'key',
      id: 'keyboard',
      actions: [{ type: 'keyUp', value: '' }]
    }])
    await browser.$("aria/Girl last name").setValue("J")
    await browser.$("aria/Girl last name").setValue("R")
    await browser.$("aria/Girl last name").setValue("Roy")
    await browser.$("//*[@id=\"collapse0\"]/div/form/div[4]/div/div").click()
    await browser.$("//*[@id=\"ethnicity-B-36701085-0\"]/div[1]/div/div[2]").click()
    await browser.$("#a89752e636df-1").click()
    await browser.$("//*[@id=\"race-B-36701085-0\"]/div[1]/div/div[2]").click()
    await browser.$("#ad3b6229de12-1").click()
    await browser.$("//*[@id=\"collapse0\"]/div/form/div[8]/div[1]/div/div/button/span").click()
    await browser.$("aria/Select year").click()
    await browser.$("aria/Select year").setValue("2013")
    await browser.$("aria/Saturday, June 8, 2013").click()
    await browser.$("aria/School Attending").click()
    await browser.$("aria/School Attending").setValue("home")
    await browser.$("aria/Home Schooled ").click()
    await browser.$("aria/Phone number").click()
    await browser.$("aria/Phone number").setValue("(111) 111-1111")
    await browser.$("//*[@id=\"collapse0\"]/div/form/div[9]").click()
    await browser.$("//*[@id=\"collapse0\"]/div/form/div[9]/div[2]/ng-select/div[1]/div/div[2]").click()
    await browser.$("#a6168a40f14b-1").click()
    await browser.$("aria/[role=\"main\"]").click()
    await browser.$("aria/[role=\"main\"]").setValue("netsutra.swain@gmail.com")
    await browser.$("//*[@id=\"collapse0\"]/div/form/div[5]/div/div/app-address-form/form/div[3]/input").setValue("10001")
    await browser.$("//*[@id=\"collapse0\"]/div/form/div[5]/div/div/app-address-form/form/div[4]/input").setValue("New York")
    await browser.$("//*[@id=\"country\"]").setValue("India")
    await browser.$("//*[@id=\"collapse0\"]/div/form/div[5]/div").click()
    await browser.$("//*[@id=\"collapse0\"]/div/form/div[11]/div[1]/div[2]/div").click()
    await browser.$("//*[@id=\"relationshipCG-B-36701085-0-cg1\"]/div[1]/div/div[2]").click()
    await browser.$("#a474db786db0-0").click()
    await browser.$("//*[@id=\"genderCG-B-36701085-0-cg1\"]/div[1]/div/div[3]").click()
    await browser.$("#a78a91e2d010-1").click()
    await browser.$("//*[@id=\"collapse0\"]/div/form/div[11]/div[2]/div[5]/div/div").click()
    await browser.$("//*[@id=\"collapse0\"]/div/form/div[11]/div[2]/div[6]/div[1]/div/app-address-form/form/div[2]/input").click()
    await browser.$("//*[@id=\"collapse0\"]/div/form/div[11]/div[2]/div[6]/div[1]/div/app-address-form/form/div[2]/input").setValue("Test 2")
    await browser.$("//*[@id=\"collapse0\"]/div/form/div[12]/div/div").click()
    await browser.$("//*[@id=\"collapse0\"]/div/form/div[16]/div/div[1]/label").click()
    await browser.$("//*[@id=\"collapse0\"]/div/form/div[16]/div/div[1]").click()
    await browser.$("aria/SAVE DETAILS").click()
    await browser.$("//*[@id=\"grade-B-36701085-0\"]/div[1]/div/div[2]").click()
    await browser.$("#a321a8e84bd1-2").click()
    await browser.$("//*[@id=\"troop-g-B-36701085-0\"]/div[1]/div/div[2]").click()
    await browser.$("aria/CT TROOP 27545 ").click()
    await browser.$("aria/SAVE DETAILS").click()
    await browser.$("aria/[role=\"main\"]").setValue("s.swain@netsutra.com")
    await browser.$("//*[@id=\"collapse0\"]/div/form/div[9]").click()
    await browser.$("aria/SAVE DETAILS").click()
    await browser.$("aria/REVIEW CART").click()
    await browser.$("#isTermsAndConditions").click()
    await browser.$("aria/ADD PAYMENT DETAILS").click()
    await browser.$("aria/Cardholder first name").click()
    await browser.$("aria/Cardholder first name").setValue("sudhansu")
    await browser.$("aria/Cardholder last name").click()
    await browser.$("aria/Cardholder last name").setValue("Swain")
    await browser.switchToFrame(
      await browser.$('iframe[src="https://girlscouts-uat.cardconnect.com/itoke/ajax-tokenizer.html?invalidinputevent=true&useexpiry=true&usecvv=true&cardlabel=Credit/Debit%20Card%20Number&placeholder=Credit/Debit%20Card%20Number&placeholdercvv=CVV&placeholdermonth=MM&placeholderyear=YYYY&css=.error%7B+color%3A+red%3B+border-color%3Ared%3B+%7D%3Binput%7Bwidth%3A+669px%3B+max-width%3A+calc(100%25+-+16px)%3B+box-sizing%3A+border-box%3B+height%3A+160px%3B+max-height%3A+35px%3B+margin-bottom%3A+10px%3B+margin-top%3A5px%3B+margin-left%3A+0%3B+margin-right%3A+0%3B+border%3A+1px+solid+%23d3d6db%3Bpadding%3A10px%3Bfont-weight%3A+400%3Bfont-size%3A12px%3Bline-height%3A+1.5%3Bcolor%3A+%23495057%3Boutline%3A+none%3Bfont-family%3A+%22Trefoil+Sans+Regular%22%3B%7D&retry=0"]')
    )
    await browser.$("#ccnumfield").click()
    await browser.switchToFrame(
      await browser.$('iframe[src="https://girlscouts-uat.cardconnect.com/itoke/ajax-tokenizer.html?invalidinputevent=true&useexpiry=true&usecvv=true&cardlabel=Credit/Debit%20Card%20Number&placeholder=Credit/Debit%20Card%20Number&placeholdercvv=CVV&placeholdermonth=MM&placeholderyear=YYYY&css=.error%7B+color%3A+red%3B+border-color%3Ared%3B+%7D%3Binput%7Bwidth%3A+669px%3B+max-width%3A+calc(100%25+-+16px)%3B+box-sizing%3A+border-box%3B+height%3A+160px%3B+max-height%3A+35px%3B+margin-bottom%3A+10px%3B+margin-top%3A5px%3B+margin-left%3A+0%3B+margin-right%3A+0%3B+border%3A+1px+solid+%23d3d6db%3Bpadding%3A10px%3Bfont-weight%3A+400%3Bfont-size%3A12px%3Bline-height%3A+1.5%3Bcolor%3A+%23495057%3Boutline%3A+none%3Bfont-family%3A+%22Trefoil+Sans+Regular%22%3B%7D&retry=0"]')
    )
    await browser.$("#ccnumfield").setValue("4111111111111111")
    await browser.switchToFrame(
      await browser.$('iframe[src="https://girlscouts-uat.cardconnect.com/itoke/ajax-tokenizer.html?invalidinputevent=true&useexpiry=true&usecvv=true&cardlabel=Credit/Debit%20Card%20Number&placeholder=Credit/Debit%20Card%20Number&placeholdercvv=CVV&placeholdermonth=MM&placeholderyear=YYYY&css=.error%7B+color%3A+red%3B+border-color%3Ared%3B+%7D%3Binput%7Bwidth%3A+669px%3B+max-width%3A+calc(100%25+-+16px)%3B+box-sizing%3A+border-box%3B+height%3A+160px%3B+max-height%3A+35px%3B+margin-bottom%3A+10px%3B+margin-top%3A5px%3B+margin-left%3A+0%3B+margin-right%3A+0%3B+border%3A+1px+solid+%23d3d6db%3Bpadding%3A10px%3Bfont-weight%3A+400%3Bfont-size%3A12px%3Bline-height%3A+1.5%3Bcolor%3A+%23495057%3Boutline%3A+none%3Bfont-family%3A+%22Trefoil+Sans+Regular%22%3B%7D&retry=0"]')
    )
    await browser.$("#tokenform").click()
    await browser.switchToFrame(
      await browser.$('iframe[src="https://girlscouts-uat.cardconnect.com/itoke/ajax-tokenizer.html?invalidinputevent=true&useexpiry=true&usecvv=true&cardlabel=Credit/Debit%20Card%20Number&placeholder=Credit/Debit%20Card%20Number&placeholdercvv=CVV&placeholdermonth=MM&placeholderyear=YYYY&css=.error%7B+color%3A+red%3B+border-color%3Ared%3B+%7D%3Binput%7Bwidth%3A+669px%3B+max-width%3A+calc(100%25+-+16px)%3B+box-sizing%3A+border-box%3B+height%3A+160px%3B+max-height%3A+35px%3B+margin-bottom%3A+10px%3B+margin-top%3A5px%3B+margin-left%3A+0%3B+margin-right%3A+0%3B+border%3A+1px+solid+%23d3d6db%3Bpadding%3A10px%3Bfont-weight%3A+400%3Bfont-size%3A12px%3Bline-height%3A+1.5%3Bcolor%3A+%23495057%3Boutline%3A+none%3Bfont-family%3A+%22Trefoil+Sans+Regular%22%3B%7D&retry=0"]')
    )
    await browser.$("#ccexpirymonth").click()
    await browser.switchToFrame(
      await browser.$('iframe[src="https://girlscouts-uat.cardconnect.com/itoke/ajax-tokenizer.html?invalidinputevent=true&useexpiry=true&usecvv=true&cardlabel=Credit/Debit%20Card%20Number&placeholder=Credit/Debit%20Card%20Number&placeholdercvv=CVV&placeholdermonth=MM&placeholderyear=YYYY&css=.error%7B+color%3A+red%3B+border-color%3Ared%3B+%7D%3Binput%7Bwidth%3A+669px%3B+max-width%3A+calc(100%25+-+16px)%3B+box-sizing%3A+border-box%3B+height%3A+160px%3B+max-height%3A+35px%3B+margin-bottom%3A+10px%3B+margin-top%3A5px%3B+margin-left%3A+0%3B+margin-right%3A+0%3B+border%3A+1px+solid+%23d3d6db%3Bpadding%3A10px%3Bfont-weight%3A+400%3Bfont-size%3A12px%3Bline-height%3A+1.5%3Bcolor%3A+%23495057%3Boutline%3A+none%3Bfont-family%3A+%22Trefoil+Sans+Regular%22%3B%7D&retry=0"]')
    )
    await browser.$("#ccexpirymonth").setValue("4")
    await browser.switchToFrame(
      await browser.$('iframe[src="https://girlscouts-uat.cardconnect.com/itoke/ajax-tokenizer.html?invalidinputevent=true&useexpiry=true&usecvv=true&cardlabel=Credit/Debit%20Card%20Number&placeholder=Credit/Debit%20Card%20Number&placeholdercvv=CVV&placeholdermonth=MM&placeholderyear=YYYY&css=.error%7B+color%3A+red%3B+border-color%3Ared%3B+%7D%3Binput%7Bwidth%3A+669px%3B+max-width%3A+calc(100%25+-+16px)%3B+box-sizing%3A+border-box%3B+height%3A+160px%3B+max-height%3A+35px%3B+margin-bottom%3A+10px%3B+margin-top%3A5px%3B+margin-left%3A+0%3B+margin-right%3A+0%3B+border%3A+1px+solid+%23d3d6db%3Bpadding%3A10px%3Bfont-weight%3A+400%3Bfont-size%3A12px%3Bline-height%3A+1.5%3Bcolor%3A+%23495057%3Boutline%3A+none%3Bfont-family%3A+%22Trefoil+Sans+Regular%22%3B%7D&retry=0"]')
    )
    await browser.$("#ccexpiryyear").click()
    await browser.switchToFrame(
      await browser.$('iframe[src="https://girlscouts-uat.cardconnect.com/itoke/ajax-tokenizer.html?invalidinputevent=true&useexpiry=true&usecvv=true&cardlabel=Credit/Debit%20Card%20Number&placeholder=Credit/Debit%20Card%20Number&placeholdercvv=CVV&placeholdermonth=MM&placeholderyear=YYYY&css=.error%7B+color%3A+red%3B+border-color%3Ared%3B+%7D%3Binput%7Bwidth%3A+669px%3B+max-width%3A+calc(100%25+-+16px)%3B+box-sizing%3A+border-box%3B+height%3A+160px%3B+max-height%3A+35px%3B+margin-bottom%3A+10px%3B+margin-top%3A5px%3B+margin-left%3A+0%3B+margin-right%3A+0%3B+border%3A+1px+solid+%23d3d6db%3Bpadding%3A10px%3Bfont-weight%3A+400%3Bfont-size%3A12px%3Bline-height%3A+1.5%3Bcolor%3A+%23495057%3Boutline%3A+none%3Bfont-family%3A+%22Trefoil+Sans+Regular%22%3B%7D&retry=0"]')
    )
    await browser.$("#ccexpiryyear").setValue("2028")
    await browser.switchToFrame(
      await browser.$('iframe[src="https://girlscouts-uat.cardconnect.com/itoke/ajax-tokenizer.html?invalidinputevent=true&useexpiry=true&usecvv=true&cardlabel=Credit/Debit%20Card%20Number&placeholder=Credit/Debit%20Card%20Number&placeholdercvv=CVV&placeholdermonth=MM&placeholderyear=YYYY&css=.error%7B+color%3A+red%3B+border-color%3Ared%3B+%7D%3Binput%7Bwidth%3A+669px%3B+max-width%3A+calc(100%25+-+16px)%3B+box-sizing%3A+border-box%3B+height%3A+160px%3B+max-height%3A+35px%3B+margin-bottom%3A+10px%3B+margin-top%3A5px%3B+margin-left%3A+0%3B+margin-right%3A+0%3B+border%3A+1px+solid+%23d3d6db%3Bpadding%3A10px%3Bfont-weight%3A+400%3Bfont-size%3A12px%3Bline-height%3A+1.5%3Bcolor%3A+%23495057%3Boutline%3A+none%3Bfont-family%3A+%22Trefoil+Sans+Regular%22%3B%7D&retry=0"]')
    )
    await browser.$("#cccvvfield").click()
    await browser.switchToFrame(
      await browser.$('iframe[src="https://girlscouts-uat.cardconnect.com/itoke/ajax-tokenizer.html?invalidinputevent=true&useexpiry=true&usecvv=true&cardlabel=Credit/Debit%20Card%20Number&placeholder=Credit/Debit%20Card%20Number&placeholdercvv=CVV&placeholdermonth=MM&placeholderyear=YYYY&css=.error%7B+color%3A+red%3B+border-color%3Ared%3B+%7D%3Binput%7Bwidth%3A+669px%3B+max-width%3A+calc(100%25+-+16px)%3B+box-sizing%3A+border-box%3B+height%3A+160px%3B+max-height%3A+35px%3B+margin-bottom%3A+10px%3B+margin-top%3A5px%3B+margin-left%3A+0%3B+margin-right%3A+0%3B+border%3A+1px+solid+%23d3d6db%3Bpadding%3A10px%3Bfont-weight%3A+400%3Bfont-size%3A12px%3Bline-height%3A+1.5%3Bcolor%3A+%23495057%3Boutline%3A+none%3Bfont-family%3A+%22Trefoil+Sans+Regular%22%3B%7D&retry=0"]')
    )
    await browser.$("#cccvvfield").setValue("909")
    await browser.$("//*[@id=\"payment-details\"]/div/div/div[1]/div[1]").click()
    await browser.switchToFrame(
      await browser.$('iframe[src="https://girlscouts-uat.cardconnect.com/itoke/ajax-tokenizer.html?invalidinputevent=true&useexpiry=true&usecvv=true&cardlabel=Credit/Debit%20Card%20Number&placeholder=Credit/Debit%20Card%20Number&placeholdercvv=CVV&placeholdermonth=MM&placeholderyear=YYYY&css=.error%7B+color%3A+red%3B+border-color%3Ared%3B+%7D%3Binput%7Bwidth%3A+669px%3B+max-width%3A+calc(100%25+-+16px)%3B+box-sizing%3A+border-box%3B+height%3A+160px%3B+max-height%3A+35px%3B+margin-bottom%3A+10px%3B+margin-top%3A5px%3B+margin-left%3A+0%3B+margin-right%3A+0%3B+border%3A+1px+solid+%23d3d6db%3Bpadding%3A10px%3Bfont-weight%3A+400%3Bfont-size%3A12px%3Bline-height%3A+1.5%3Bcolor%3A+%23495057%3Boutline%3A+none%3Bfont-family%3A+%22Trefoil+Sans+Regular%22%3B%7D&retry=0"]')
    )
    await browser.$("#tokenform").click()
    await browser.$("aria/SUBMIT PAYMENT").click()
    await browser.$("#loginBtn").click()
  });
});
